### ISSUE TITLE
Adding suspense exchange results in data being undefined

### ISSUE THREAD

**Issue by brielov** [FormidableLabs/urql-exchange-suspense#9]
This was working fine until I addedd the suspense exchange and `suspense: true`. Now every query returns `undefined` data. If I remove the suspense exchange, data is not undefined anymore.

```js
// CustomerListView.tsx
const [{ data }] = useQuery<{ allCustomers: Customer[] }>({
    query: AllCustomersQuery,
  });

  console.log(data); // undefined
```

```js
// index.tsx
const client = createClient({
  url: `${process.env.ENDPOINT!}/graphql`,
  fetchOptions: () => {
    const token = localStorage.getItem('token');
    return {
      headers: { authorization: token ? `Bearer ${token}` : '' },
    };
  },
  suspense: true,
  exchanges: [dedupExchange, suspenseExchange, fetchExchange],
});
```

Am I missing something? Or is this a known bug?

Note: In the network panel the query executes correctly and returns the correct data.

**Comment by JoviDeCroock** [comment]
Hey @brielov 

Would you mind adding the `cacheExchange` after your `suspenseExchange` as mentioned in the `README`? Does that work?

```
Important: In React Suspense when a piece of data is still loading, a promise will be thrown that tells React to wait for this promise to complete and try rendering the suspended component again. The suspenseExchange works by caching the result of any operation until React retries, but it doesn't replace the cacheExchange, since it only briefly keeps the result around.

This means that, in your array of Exchanges, the suspenseExchange should be added after the dedupExchange and before the cacheExchange.
```

**Comment by brielov** [comment]
Hi @JoviDeCroock, cacheExchange is in fact after suspenseExchange, this is how it looks right now.

```js
const client = createClient({
  url: `${process.env.ENDPOINT!}/graphql`,
  fetchOptions: () => {
    const token = localStorage.getItem('token');
    return {
      headers: { authorization: token ? `Bearer ${token}` : '' },
    };
  },
  suspense: true,
  exchanges: [dedupExchange, suspenseExchange, cacheExchange(), fetchExchange],
});
```

I don't know if it is relevant, but this is happening on a lazy loaded component.

**Comment by JoviDeCroock** [comment]
What cacheExchange are you using?

**Comment by brielov** [comment]
@JoviDeCroock I'm using `@urql/exchange-graphcache` as it is. Is this ok?

**Comment by JoviDeCroock** [comment]
It does not seem to introduce any issues here, we might have to first find out what your issue exactly is https://codesandbox.io/s/urql-client-side-suspense-demo-e9iuk

**Comment by brielov** [comment]
@JoviDeCroock  I've seen that demo today, I've switched the `Main.js` module to be a lazy loaded module and it seems to work fine. My codebase is almost exactly the same as the example.

**Comment by JoviDeCroock** [comment]
There will be a slight difference somewhere but without sufficient information I can only guess.

**Comment by brielov** [comment]
@JoviDeCroock So, I just updated urql 1.8.1 to 1.8.2 and works now, so strange 🤦🏻‍♂️
Thanks for the quick feedback, much appreciated!
